version: '3.8'

services:
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=example
        - POSTGRES_USER=dbuser
        - POSTGRES_DB=testdb
      volumes:
        - ./database:/var/lib/postgresql/data
      container_name: ex-2.9-db
    backend:
      image: example-backend
      ports:
        - "8080:8080"
      environment:
        - REDIS_HOST=ex-2.9-redis
        - POSTGRES_HOST=ex-2.9-db
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=example
        - POSTGRES_DATABASE=testdb
      container_name: ex-2.9-backend
      depends_on:
        - db
    frontend:
      image: example-frontend
      ports:
        - "5000:5000"
      container_name: ex-2.9-frontend
    redis:
      image: redis
      container_name: ex-2.9-redis
      command: --save 10 1 --loglevel warning
      volumes:
        - ./data:/data
