version: '3.8'

services:
    training:
      build: ml-kurkkumopo-training
      container_name: example-ml-training
      volumes:
        - model:/src/model
    backend:
      build: ml-kurkkumopo-backend
      ports:
        - "5000:5000"
      volumes:
        - model:/src/model
      depends_on:
        - training
      container_name: example-ml-backend
    frontend:
      build: ml-kurkkumopo-frontend
      ports:
        - "3000:3000"
      container_name: example-ml-frontend

volumes:
  model: