version: '3.8'

services:
    proxy:
      image: nginx:1.19-alpine
      restart: unless-stopped
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
      container_name: ex-2.8-nginx-proxy
      depends_on:
        - frontend
        - backend
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=example
        - POSTGRES_USER=dbuser
        - POSTGRES_DB=testdb
      container_name: ex-2.8-db
    backend:
      image: example-backend
      environment:
        - REDIS_HOST=ex-2.8-redis
        - POSTGRES_HOST=ex-2.8-db
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=example
        - POSTGRES_DATABASE=testdb
      container_name: ex-2.8-backend
      depends_on:
        - db
        - redis
    frontend:
      image: example-frontend
      container_name: ex-2.8-frontend
    redis:
      image: redis
      container_name: ex-2.8-redis
